rule('c')
  add_deps('mode.release', 'mode.debug')
  add_orders('mode.release', 'mode.debug')
  on_config(function(target)
    target:set('warnings', 'allextra', 'error', 'pedantic')
    target:set('toolchains', 'gcc')
    target:set('languages', 'c11')
  end)
rule_end()
