rule('clike')
  on_config(function(target)
    target:set_toolchains('mode.release', 'mode.debug', 'mode.tsan', 'mode.asan')
    target:set_cflags('-Wall', '-Werror', '-Wextra', '-pedantic')
    target:set_toolchains('gcc')
  end)
rule_end()

rule('cxx')
  add_deps('clike')
  on_config(function(target)
    target:set_languages('cxx17')
  end)
rule_end()

rule('c')
  add_deps('clike')
  on_config(function(target)
    target:set_languages('c11')
  end)
rule_end()
